// sqlite_filtered.go — mirror helpers of the GameRounds query API that
// restrict results to rounds with RoundCode LIKE 'GA%' (i.e. generated by
// cmd/race-generator, not captured from the DS vendor).
//
// Used by the upcoming cmd/race-broadcaster (Plan 02 / docs/racegen-design/
// 03-RACE-BROADCASTER.md) so the /tv, /pos and /web endpoints only expose
// generated rounds, never mixing DS-captured ones in by accident.
//
// CONSTRAINT (per Task 1): zero changes to sqlite.go. We intentionally do
// NOT reuse the package-level prepared statements stmtHistory / stmtFuture
// because they encode a fixed WHERE clause; adding the LIKE filter would
// require either re-preparing them (mutates Init()) or maintaining a
// parallel set of *GA prepared statements with their own lazy-init
// machinery. Both options bleed into sqlite.go's lifecycle, so we instead
// build the queries ad-hoc here.
//
// Performance: each call costs one extra prepare/plan cycle vs. the
// originals. The race-broadcaster is a single low-QPS process (init at
// connect, gameStart on tick) — measured cost is negligible. If profiling
// later shows otherwise, we can add a dedicated prepared-statement
// lifecycle for these helpers in a follow-up that intentionally touches
// sqlite.go.
package sqlite

import (
	"fmt"
	"strings"
	"time"

	"vg-racegen/internal/models"
)

// nowSQLite returns the current UTC time formatted to match the
// 'YYYY-MM-DD HH:MM:SS' string stored in GameRounds.VideoStartDt /
// VideoEndDt. Lexicographic comparison of that fixed-width format is a
// correct chronological comparison, so the GA helpers below can split
// past vs. future with a plain string `<=` / `>` against this value.
//
// Why time-based (not Status-based) for GA: the race-generator
// pre-computes every GA round's outcome and persists it with Status='F'
// the moment it's created (see internal/raceserver/broadcast.go header).
// So unlike the DS path — where the vendor flips a round O→F when it
// finishes, making Status a faithful proxy for "has this race happened
// yet" — every GA round is 'F' regardless of whether its video has
// played. The real "happened yet" signal for GA is VideoEndDt vs now,
// which is exactly the boundary the DS O/F transition encodes. Using it
// here keeps the in-progress round (started, not yet ended) in the
// "open/future" bucket, mirroring DS Status='O'.
func nowSQLite() string {
	return time.Now().UTC().Format("2006-01-02 15:04:05")
}

// Column list reuse: gameRoundSelectCols is already declared in mobile.go
// as a package-level const (with the same byte content the stmtHistory /
// stmtFuture / stmtAfterGame prepared statements in sqlite.go use). We
// piggy-back on that existing constant so any future column drift is
// caught in one place.

// GamesWindowGA is the GA-only mirror of GamesWindow: returns history
// (finished, ASC) + future (open, ASC) for a betoffer, restricted to
// rounds whose RoundCode starts with "GA".
func GamesWindowGA(betofferID int, historyCount int, futureCount int) ([]*models.GameRound, error) {
	now := nowSQLite()

	// History: GA rounds whose video has already ended, most recent first
	// (then reversed below). VideoEndDt<=now mirrors DS Status='F'.
	historyQ := `SELECT ` + gameRoundSelectCols + `
		FROM GameRounds
		WHERE GameTypeId=? AND RoundCode LIKE 'GA%' AND VideoEndDt<=?
		ORDER BY VideoStartDt DESC
		LIMIT ?`
	historyRows, err := db.Query(historyQ, betofferID, now, abs(historyCount))
	if err != nil {
		return nil, fmt.Errorf("query history GA: %w", err)
	}
	defer historyRows.Close()

	history, err := scanGameRounds(historyRows)
	if err != nil {
		return nil, fmt.Errorf("scan history GA: %w", err)
	}

	// Reverse history so it's ASC by VideoStartDt (matches GamesWindow).
	for i, j := 0, len(history)-1; i < j; i, j = i+1, j-1 {
		history[i], history[j] = history[j], history[i]
	}

	// Future: GA rounds still playing or yet to start (VideoEndDt>now),
	// ASC by VideoStartDt. Includes the in-progress round, mirroring DS
	// Status='O'.
	futureQ := `SELECT ` + gameRoundSelectCols + `
		FROM GameRounds
		WHERE GameTypeId=? AND RoundCode LIKE 'GA%' AND VideoEndDt>?
		ORDER BY VideoStartDt ASC
		LIMIT ?`
	futureRows, err := db.Query(futureQ, betofferID, now, futureCount)
	if err != nil {
		return nil, fmt.Errorf("query future GA: %w", err)
	}
	defer futureRows.Close()

	future, err := scanGameRounds(futureRows)
	if err != nil {
		return nil, fmt.Errorf("scan future GA: %w", err)
	}

	out := make([]*models.GameRound, 0, len(history)+len(future))
	out = append(out, history...)
	out = append(out, future...)
	return out, nil
}

// GamesDayGA returns EVERY GA round for a betoffer whose VideoStartDt
// falls within a single day, ASC by VideoStartDt. Unlike GamesWindowGA it
// is not a sliding [history,future] window: it serves the full day for
// offline analysis (GET /games/day). dayStart/dayEnd are the inclusive
// lower / exclusive upper bounds in the stored 'YYYY-MM-DD HH:MM:SS'
// format (e.g. "2026-06-04 00:00:00" .. "2026-06-05 00:00:00"); string
// comparison on that fixed-width format is a correct chronological range.
//
// Note: the broadcaster only returns what the race-generator has actually
// persisted. A full day forward (~360 dog rounds) requires the generator
// to have pre-staged it (RACEGEN_HORIZON); otherwise this returns the
// past + the current horizon only.
func GamesDayGA(betofferID int, dayStart, dayEnd string) ([]*models.GameRound, error) {
	q := `SELECT ` + gameRoundSelectCols + `
		FROM GameRounds
		WHERE GameTypeId=? AND RoundCode LIKE 'GA%' AND VideoStartDt>=? AND VideoStartDt<?
		ORDER BY VideoStartDt ASC`
	rows, err := db.Query(q, betofferID, dayStart, dayEnd)
	if err != nil {
		return nil, fmt.Errorf("query day GA: %w", err)
	}
	defer rows.Close()
	return scanGameRounds(rows)
}

// UpcomingGamesGA is the GA-only mirror of UpcomingGames: next N open
// GA rounds for a betoffer, ASC by VideoStartDt.
func UpcomingGamesGA(betofferID int, limit int) ([]*models.GameRound, error) {
	q := `SELECT ` + gameRoundSelectCols + `
		FROM GameRounds
		WHERE GameTypeId=? AND RoundCode LIKE 'GA%' AND VideoEndDt>?
		ORDER BY VideoStartDt ASC
		LIMIT ?`
	rows, err := db.Query(q, betofferID, nowSQLite(), limit)
	if err != nil {
		return nil, fmt.Errorf("query upcoming GA: %w", err)
	}
	defer rows.Close()
	return scanGameRounds(rows)
}

// CurrentGameGA is the GA-only mirror of CurrentGame: the first open GA
// round for a betoffer. Returns an error (mirroring CurrentGame) when no
// open GA round exists.
func CurrentGameGA(betofferID int) (*models.GameRound, error) {
	games, err := UpcomingGamesGA(betofferID, 1)
	if err != nil {
		return nil, err
	}
	if len(games) == 0 {
		return nil, fmt.Errorf("no upcoming GA games for betoffer %d", betofferID)
	}
	return games[0], nil
}

// RecentResultsGA is the GA-only mirror of RecentResults: last N finished
// GA rounds for a betoffer with their results.
//
// Always returns a non-nil result map (possibly empty) so callers can
// safely range it.
func RecentResultsGA(betofferID int, limit int) ([]*models.GameRound, map[string][]models.GameResult, error) {
	q := `SELECT ` + gameRoundSelectCols + `
		FROM GameRounds
		WHERE GameTypeId=? AND RoundCode LIKE 'GA%' AND VideoEndDt<=?
		ORDER BY VideoStartDt DESC
		LIMIT ?`
	rows, err := db.Query(q, betofferID, nowSQLite(), limit)
	if err != nil {
		return nil, nil, fmt.Errorf("query recent results GA: %w", err)
	}
	defer rows.Close()

	games, err := scanGameRounds(rows)
	if err != nil {
		return nil, nil, fmt.Errorf("scan recent results GA: %w", err)
	}

	codes := make([]string, len(games))
	for i, g := range games {
		codes[i] = g.RoundCode
	}

	resultMap, err := ResultsBatch(codes)
	if err != nil {
		return nil, nil, err
	}
	if resultMap == nil {
		resultMap = make(map[string][]models.GameResult)
	}
	return games, resultMap, nil
}

// =====================================================================
// Plan 04 DS-ISOLATION — DS-only mirror helpers.
//
// Same pattern as the *GA siblings above: ad-hoc queries (no touching of
// sqlite.go's prepared statements) with `AND RoundCode NOT LIKE 'GA%'`.
// The three caller-side helpers (GamesByRoundCodesDS, GameByRoundCodeDS,
// ResultsByRoundCodeDS) delegate to their unsuffixed siblings after a
// cheap prefix check so callers that accidentally pass a GA code don't
// trigger any IO and don't get a leaked GA payload.
// =====================================================================

// GamesWindowDS is the DS-only mirror of GamesWindow: returns history
// (finished, ASC) + future (open, ASC) for a betoffer, restricted to
// rounds whose RoundCode does NOT start with "GA" (i.e. captured by the
// DS vendor collectors, never generated by race-generator).
func GamesWindowDS(betofferID int, historyCount int, futureCount int) ([]*models.GameRound, error) {
	historyQ := `SELECT ` + gameRoundSelectCols + `
		FROM GameRounds
		WHERE GameTypeId=? AND Status='F' AND RoundCode NOT LIKE 'GA%'
		ORDER BY VideoStartDt DESC
		LIMIT ?`
	historyRows, err := db.Query(historyQ, betofferID, abs(historyCount))
	if err != nil {
		return nil, fmt.Errorf("query history DS: %w", err)
	}
	defer historyRows.Close()

	history, err := scanGameRounds(historyRows)
	if err != nil {
		return nil, fmt.Errorf("scan history DS: %w", err)
	}

	// Reverse history so it's ASC by VideoStartDt (matches GamesWindow).
	for i, j := 0, len(history)-1; i < j; i, j = i+1, j-1 {
		history[i], history[j] = history[j], history[i]
	}

	futureQ := `SELECT ` + gameRoundSelectCols + `
		FROM GameRounds
		WHERE GameTypeId=? AND Status='O' AND RoundCode NOT LIKE 'GA%'
		ORDER BY VideoStartDt ASC
		LIMIT ?`
	futureRows, err := db.Query(futureQ, betofferID, futureCount)
	if err != nil {
		return nil, fmt.Errorf("query future DS: %w", err)
	}
	defer futureRows.Close()

	future, err := scanGameRounds(futureRows)
	if err != nil {
		return nil, fmt.Errorf("scan future DS: %w", err)
	}

	out := make([]*models.GameRound, 0, len(history)+len(future))
	out = append(out, history...)
	out = append(out, future...)
	return out, nil
}

// UpcomingGamesDS is the DS-only mirror of UpcomingGames: next N open
// DS rounds for a betoffer, ASC by VideoStartDt.
func UpcomingGamesDS(betofferID int, limit int) ([]*models.GameRound, error) {
	q := `SELECT ` + gameRoundSelectCols + `
		FROM GameRounds
		WHERE GameTypeId=? AND Status='O' AND RoundCode NOT LIKE 'GA%'
		ORDER BY VideoStartDt ASC
		LIMIT ?`
	rows, err := db.Query(q, betofferID, limit)
	if err != nil {
		return nil, fmt.Errorf("query upcoming DS: %w", err)
	}
	defer rows.Close()
	return scanGameRounds(rows)
}

// CurrentGameDS is the DS-only mirror of CurrentGame: the first open DS
// round for a betoffer. Returns an error (mirroring CurrentGame) when no
// open DS round exists.
func CurrentGameDS(betofferID int) (*models.GameRound, error) {
	games, err := UpcomingGamesDS(betofferID, 1)
	if err != nil {
		return nil, err
	}
	if len(games) == 0 {
		return nil, fmt.Errorf("no upcoming DS games for betoffer %d", betofferID)
	}
	return games[0], nil
}

// RecentResultsDS is the DS-only mirror of RecentResults: last N finished
// DS rounds for a betoffer plus their results.
//
// Always returns a non-nil result map (possibly empty) so callers can
// safely range it.
func RecentResultsDS(betofferID, limit int) ([]*models.GameRound, map[string][]models.GameResult, error) {
	q := `SELECT ` + gameRoundSelectCols + `
		FROM GameRounds
		WHERE GameTypeId=? AND Status='F' AND RoundCode NOT LIKE 'GA%'
		ORDER BY VideoStartDt DESC
		LIMIT ?`
	rows, err := db.Query(q, betofferID, limit)
	if err != nil {
		return nil, nil, fmt.Errorf("query recent results DS: %w", err)
	}
	defer rows.Close()

	games, err := scanGameRounds(rows)
	if err != nil {
		return nil, nil, fmt.Errorf("scan recent results DS: %w", err)
	}

	codes := make([]string, len(games))
	for i, g := range games {
		codes[i] = g.RoundCode
	}

	resultMap, err := ResultsBatch(codes)
	if err != nil {
		return nil, nil, err
	}
	if resultMap == nil {
		resultMap = make(map[string][]models.GameResult)
	}
	return games, resultMap, nil
}

// GamesByRoundCodesDS is the DS-only mirror of GamesByRoundCodes: it
// strips any GA-prefixed code from the caller's slice before delegating
// to GamesByRoundCodes, so no GA round can ever bleed back through.
// Returns (nil, nil) when the filtered slice is empty (matches the
// behaviour of GamesByRoundCodes on an empty input).
func GamesByRoundCodesDS(codes []string) ([]*models.GameRound, error) {
	if len(codes) == 0 {
		return nil, nil
	}
	filtered := make([]string, 0, len(codes))
	for _, c := range codes {
		if !strings.HasPrefix(c, "GA") {
			filtered = append(filtered, c)
		}
	}
	if len(filtered) == 0 {
		return nil, nil
	}
	return GamesByRoundCodes(filtered)
}

// GameByRoundCodeDS is the DS-only mirror of GameByRoundCode: returns
// (nil, nil) for GA-prefixed codes without touching the DB. Callers on
// the DS path treat "no DS round for this code" as a legitimate absence
// rather than an error, so we surface no error here either.
func GameByRoundCodeDS(roundCode string) (*models.GameRound, error) {
	if strings.HasPrefix(roundCode, "GA") {
		return nil, nil
	}
	return GameByRoundCode(roundCode)
}

// GamesAfterGameIDDS is the DS-only mirror of GamesAfterGameID. The
// pivot (`gameID`) is looked up unfiltered — callers on the DS path only
// pass DS codes by construction — but the returned window has
// `RoundCode NOT LIKE 'GA%'` so GA rounds inserted between the pivot
// and "now" can never sneak into the DS path's resync slice.
func GamesAfterGameIDDS(betofferID int, gameID string, limit int) ([]*models.GameRound, error) {
	var pivotStartDt string
	if err := db.QueryRow(
		`SELECT VideoStartDt FROM GameRounds WHERE RoundCode=?`,
		gameID,
	).Scan(&pivotStartDt); err != nil {
		return nil, fmt.Errorf("pivot lookup DS for %s: %w", gameID, err)
	}
	q := `SELECT ` + gameRoundSelectCols + `
		FROM GameRounds
		WHERE GameTypeId=? AND VideoStartDt > ? AND RoundCode NOT LIKE 'GA%'
		ORDER BY VideoStartDt ASC
		LIMIT ?`
	rows, err := db.Query(q, betofferID, pivotStartDt, limit)
	if err != nil {
		return nil, fmt.Errorf("query after DS: %w", err)
	}
	defer rows.Close()
	return scanGameRounds(rows)
}

// StatsHistoryDS is the DS-only mirror of StatsHistory: history rows
// (each = the finish positions of a round), newest/oldest RoundCode of
// the window. Same shape and semantics as StatsHistory, but restricted
// to DS rounds. Returns ([][]int{}, "", "", nil) when the betoffer has
// no finished DS rounds (matches StatsHistory's empty-window contract).
func StatsHistoryDS(betofferID, limit int) (history [][]int, newest, oldest string, err error) {
	q := `SELECT RoundCode FROM GameRounds
		WHERE GameTypeId=? AND Status='F' AND RoundCode NOT LIKE 'GA%'
		ORDER BY VideoStartDt DESC LIMIT ?`
	rows, err := db.Query(q, betofferID, limit)
	if err != nil {
		return nil, "", "", fmt.Errorf("query stats DS: %w", err)
	}
	defer rows.Close()
	var codes []string
	for rows.Next() {
		var c string
		if err := rows.Scan(&c); err != nil {
			return nil, "", "", fmt.Errorf("scan stats DS: %w", err)
		}
		codes = append(codes, c)
	}
	if err := rows.Err(); err != nil {
		return nil, "", "", err
	}
	if len(codes) == 0 {
		return [][]int{}, "", "", nil
	}
	newest = codes[0]
	oldest = codes[len(codes)-1]

	resultMap, err := ResultsBatch(codes)
	if err != nil {
		return nil, "", "", fmt.Errorf("results for stats DS: %w", err)
	}
	history = make([][]int, 0, len(codes))
	for _, c := range codes {
		results := resultMap[c]
		positions := make([]int, len(results))
		for _, r := range results {
			if r.Position >= 1 && r.Position <= len(positions) {
				positions[r.Position-1] = r.RunnerNumber
			}
		}
		history = append(history, positions)
	}
	return history, newest, oldest, nil
}

// ResultsByRoundCodeDS is the DS-only mirror of ResultsByRoundCode:
// caller-side prefix check, returns (nil, nil) for GA codes without
// hitting the DB.
func ResultsByRoundCodeDS(roundCode string) ([]models.GameResult, error) {
	if strings.HasPrefix(roundCode, "GA") {
		return nil, nil
	}
	return ResultsByRoundCode(roundCode)
}

// GamesByRoundCodesGA is the GA-only mirror of GamesByRoundCodesDS: it
// keeps only GA-prefixed codes before delegating to GamesByRoundCodes,
// so a DS round can never bleed into the GA (race-broadcaster) path.
// Returns (nil, nil) when the filtered slice is empty.
func GamesByRoundCodesGA(codes []string) ([]*models.GameRound, error) {
	if len(codes) == 0 {
		return nil, nil
	}
	filtered := make([]string, 0, len(codes))
	for _, c := range codes {
		if strings.HasPrefix(c, "GA") {
			filtered = append(filtered, c)
		}
	}
	if len(filtered) == 0 {
		return nil, nil
	}
	return GamesByRoundCodes(filtered)
}

// GameByRoundCodeGA is the GA-only mirror of GameByRoundCodeDS: returns
// (nil, nil) for non-GA codes without touching the DB. Callers on the
// GA path treat "no GA round for this code" as a legitimate absence.
func GameByRoundCodeGA(roundCode string) (*models.GameRound, error) {
	if !strings.HasPrefix(roundCode, "GA") {
		return nil, nil
	}
	return GameByRoundCode(roundCode)
}

// ResultsByRoundCodeGA is the GA-only mirror of ResultsByRoundCodeDS:
// caller-side prefix check, returns (nil, nil) for non-GA codes without
// hitting the DB.
func ResultsByRoundCodeGA(roundCode string) ([]models.GameResult, error) {
	if !strings.HasPrefix(roundCode, "GA") {
		return nil, nil
	}
	return ResultsByRoundCode(roundCode)
}
