// sqlite_filtered_test.go — TDD tests for the *GA helpers added in
// internal/sqlite/sqlite_filtered.go (Plan 02 Task 1 of the race-broadcaster).
//
// These helpers MUST behave exactly like their unsuffixed siblings except
// they restrict results to rounds whose RoundCode starts with "GA"
// (i.e. rounds generated by cmd/race-generator, not captured from DS).
//
// The tests also include a regression check on GamesWindow to assert that
// the unsuffixed function continues to return ALL rounds (no behavioural
// drift from adding the new helpers).
package sqlite

import (
	"fmt"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"vg-racegen/internal/models"
)

// toRoundCodeNumeric builds a synthetic numeric round code like
// "541_105_20260520_120000_001" (the prefix race-broadcaster must filter OUT).
func toRoundCodeNumeric(betoffer int, ts time.Time, n int) string {
	return fmt.Sprintf("%d_%d_%s_%03d", betoffer, 105, ts.UTC().Format("20060102_150405"), n)
}

// toRoundCodeGA builds a synthetic generated round code like
// "GA541_105_20260520_120000_001" (the prefix that *GA helpers must keep).
func toRoundCodeGA(betoffer int, ts time.Time, n int) string {
	return "GA" + toRoundCodeNumeric(betoffer, ts, n)
}

// seedMixedRounds inserts 3 DS-style rounds (numeric prefix, finished) and
// 3 GA-style rounds (GA prefix, open) for a given betoffer so the helpers
// can be exercised against a realistic mix.
func seedMixedRounds(t *testing.T, betoffer int) {
	t.Helper()
	now := time.Now().UTC().Truncate(time.Second)

	mk := func(code, gameType string, ts time.Time, status string) {
		var finishedAt *string
		if status == "F" {
			s := ts.Add(45 * time.Second).Format(time.RFC3339)
			finishedAt = &s
		}
		gr := &models.GameRound{
			RoundCode:    code,
			GameTypeID:   betoffer,
			GameType:     gameType,
			Status:       status,
			VideoStartDt: ts.Format("2006-01-02 15:04:05"),
			VideoEndDt:   ts.Add(45 * time.Second).Format("2006-01-02 15:04:05"),
			CreatedAt:    ts.Format(time.RFC3339),
			FinishedAt:   finishedAt,
		}
		if _, err := UpsertGameRound(gr); err != nil {
			t.Fatalf("upsert %s: %v", code, err)
		}
	}

	// 3 DS-captured rounds in the past, all finished.
	for i := 0; i < 3; i++ {
		ts := now.Add(time.Duration(-i-10) * time.Minute)
		mk(toRoundCodeNumeric(betoffer, ts, i), "dog8", ts, "F")
	}
	// 3 GA-generated rounds in the future, all open.
	for i := 0; i < 3; i++ {
		ts := now.Add(time.Duration(i+1) * time.Minute)
		mk(toRoundCodeGA(betoffer, ts, i), "dog8", ts, "O")
	}
}

// seedMixedRoundsWithFinishedGA additionally inserts 2 GA rounds that are
// already finished so RecentResultsGA / GamesWindowGA history side can find
// them.
func seedMixedRoundsWithFinishedGA(t *testing.T, betoffer int) {
	t.Helper()
	seedMixedRounds(t, betoffer)

	now := time.Now().UTC().Truncate(time.Second)
	mk := func(code string, ts time.Time) {
		finished := ts.Add(45 * time.Second).Format(time.RFC3339)
		gr := &models.GameRound{
			RoundCode:    code,
			GameTypeID:   betoffer,
			GameType:     "dog8",
			Status:       "F",
			VideoStartDt: ts.Format("2006-01-02 15:04:05"),
			VideoEndDt:   ts.Add(45 * time.Second).Format("2006-01-02 15:04:05"),
			CreatedAt:    ts.Format(time.RFC3339),
			FinishedAt:   &finished,
		}
		if _, err := UpsertGameRound(gr); err != nil {
			t.Fatalf("upsert %s: %v", code, err)
		}
	}
	for i := 0; i < 2; i++ {
		// Use a wider offset so codes don't collide with the open GA seeds.
		ts := now.Add(time.Duration(-i-30) * time.Minute)
		mk(toRoundCodeGA(betoffer, ts, 100+i), ts)
	}
}

func TestGamesWindowGA_OnlyReturnsGARounds(t *testing.T) {
	resetForTest(t)
	if err := Init(filepath.Join(t.TempDir(), "ga_window.db")); err != nil {
		t.Fatalf("init: %v", err)
	}
	defer resetForTest(t)

	const betoffer = 541
	seedMixedRoundsWithFinishedGA(t, betoffer)

	rounds, err := GamesWindowGA(betoffer, 10, 10)
	if err != nil {
		t.Fatalf("GamesWindowGA: %v", err)
	}
	// 2 finished GA + 3 open GA = 5.
	if len(rounds) != 5 {
		t.Fatalf("GamesWindowGA len=%d, want 5; rounds=%v", len(rounds), roundCodes(rounds))
	}
	for _, r := range rounds {
		if len(r.RoundCode) < 2 || r.RoundCode[:2] != "GA" {
			t.Fatalf("non-GA round leaked: %s", r.RoundCode)
		}
	}
}

// TestGamesWindowGA_AllFinishedStatus reproduces the production data shape:
// the race-generator persists EVERY GA round with Status='F' (outcome baked
// in at generation time), so the past/future split must come from VideoEndDt
// vs. now, NOT from Status. A Status-based split would put every round in
// the history bucket (Status='F') and leave the future bucket empty, so the
// webview would receive an all-past (or, with DESC+LIMIT, all-furthest-future)
// window with no playable "now" round → err_setup. This test seeds rounds
// straddling now, all Status='F', and asserts the window straddles correctly.
func TestGamesWindowGA_AllFinishedStatus(t *testing.T) {
	resetForTest(t)
	if err := Init(filepath.Join(t.TempDir(), "ga_allF.db")); err != nil {
		t.Fatalf("init: %v", err)
	}
	defer resetForTest(t)

	const betoffer = 541
	now := time.Now().UTC().Truncate(time.Second)
	mk := func(ts time.Time, n int) {
		finished := ts.Add(45 * time.Second).Format(time.RFC3339)
		gr := &models.GameRound{
			RoundCode:    toRoundCodeGA(betoffer, ts, n),
			GameTypeID:   betoffer,
			GameType:     "dog8",
			Status:       "F", // every GA round is persisted finished
			VideoStartDt: ts.Format("2006-01-02 15:04:05"),
			VideoEndDt:   ts.Add(45 * time.Second).Format("2006-01-02 15:04:05"),
			CreatedAt:    ts.Format(time.RFC3339),
			FinishedAt:   &finished,
		}
		if _, err := UpsertGameRound(gr); err != nil {
			t.Fatalf("upsert: %v", err)
		}
	}
	// 6 past rounds (ended before now) + the in-progress round (started 10s
	// ago, ends in 35s) + 5 strictly-future rounds.
	for i := 1; i <= 6; i++ {
		mk(now.Add(time.Duration(-i)*4*time.Minute), i)
	}
	mk(now.Add(-10*time.Second), 100) // in-progress: VideoEndDt > now
	for i := 1; i <= 5; i++ {
		mk(now.Add(time.Duration(i)*4*time.Minute), 200+i)
	}

	rounds, err := GamesWindowGA(betoffer, 8, 10)
	if err != nil {
		t.Fatalf("GamesWindowGA: %v", err)
	}
	// history = VideoEndDt<=now (the 6 past) ; future = VideoEndDt>now (the
	// in-progress + 5 strictly-future = 6). Total 12.
	if len(rounds) != 12 {
		t.Fatalf("len=%d, want 12; rounds=%v", len(rounds), roundCodes(rounds))
	}
	// The window must be ASC by VideoStartDt and straddle now: at least one
	// round before now and at least one round whose video has not yet ended.
	var beforeNow, openNow int
	nowStr := now.Format("2006-01-02 15:04:05")
	for _, r := range rounds {
		if r.VideoEndDt <= nowStr {
			beforeNow++
		} else {
			openNow++
		}
	}
	if beforeNow == 0 || openNow == 0 {
		t.Fatalf("window does not straddle now: before=%d open=%d", beforeNow, openNow)
	}
	if openNow != 6 {
		t.Errorf("open/future side = %d, want 6 (in-progress + 5 future)", openNow)
	}
}

func TestCurrentGameGA_OnlyReturnsGA(t *testing.T) {
	resetForTest(t)
	if err := Init(filepath.Join(t.TempDir(), "ga_current.db")); err != nil {
		t.Fatalf("init: %v", err)
	}
	defer resetForTest(t)

	const betoffer = 541
	seedMixedRounds(t, betoffer)

	gr, err := CurrentGameGA(betoffer)
	if err != nil {
		t.Fatalf("CurrentGameGA: %v", err)
	}
	if gr == nil {
		t.Fatal("CurrentGameGA: nil round")
	}
	if len(gr.RoundCode) < 2 || gr.RoundCode[:2] != "GA" {
		t.Fatalf("CurrentGameGA returned non-GA: %s", gr.RoundCode)
	}
}

func TestCurrentGameGA_ErrorsWhenNoGAOpen(t *testing.T) {
	resetForTest(t)
	if err := Init(filepath.Join(t.TempDir(), "ga_current_empty.db")); err != nil {
		t.Fatalf("init: %v", err)
	}
	defer resetForTest(t)

	const betoffer = 541
	// Seed ONLY DS rounds (no GA at all) so CurrentGameGA should error out
	// even though CurrentGame would have returned something.
	now := time.Now().UTC().Truncate(time.Second)
	for i := 0; i < 3; i++ {
		ts := now.Add(time.Duration(i+1) * time.Minute)
		gr := &models.GameRound{
			RoundCode:    toRoundCodeNumeric(betoffer, ts, i),
			GameTypeID:   betoffer,
			GameType:     "dog8",
			Status:       "O",
			VideoStartDt: ts.Format("2006-01-02 15:04:05"),
			VideoEndDt:   ts.Add(45 * time.Second).Format("2006-01-02 15:04:05"),
			CreatedAt:    ts.Format(time.RFC3339),
		}
		if _, err := UpsertGameRound(gr); err != nil {
			t.Fatalf("seed DS: %v", err)
		}
	}

	if _, err := CurrentGameGA(betoffer); err == nil {
		t.Fatal("CurrentGameGA: want error when only DS rounds exist, got nil")
	}
	// CurrentGame (unfiltered) must still succeed — proves the filter is
	// scoped to the new helper and didn't alter the original.
	if _, err := CurrentGame(betoffer); err != nil {
		t.Fatalf("CurrentGame (unfiltered) regressed: %v", err)
	}
}

func TestUpcomingGamesGA_OnlyReturnsGA(t *testing.T) {
	resetForTest(t)
	if err := Init(filepath.Join(t.TempDir(), "ga_upcoming.db")); err != nil {
		t.Fatalf("init: %v", err)
	}
	defer resetForTest(t)

	const betoffer = 541
	seedMixedRounds(t, betoffer)

	rounds, err := UpcomingGamesGA(betoffer, 10)
	if err != nil {
		t.Fatalf("UpcomingGamesGA: %v", err)
	}
	if len(rounds) != 3 {
		t.Fatalf("UpcomingGamesGA len=%d, want 3 GA; rounds=%v", len(rounds), roundCodes(rounds))
	}
	for _, r := range rounds {
		if len(r.RoundCode) < 2 || r.RoundCode[:2] != "GA" {
			t.Fatalf("non-GA round leaked: %s", r.RoundCode)
		}
		if r.Status != "O" {
			t.Fatalf("UpcomingGamesGA returned non-open round: %s status=%s", r.RoundCode, r.Status)
		}
	}
}

func TestUpcomingGamesGA_LimitWorks(t *testing.T) {
	resetForTest(t)
	if err := Init(filepath.Join(t.TempDir(), "ga_upcoming_limit.db")); err != nil {
		t.Fatalf("init: %v", err)
	}
	defer resetForTest(t)

	const betoffer = 541
	seedMixedRounds(t, betoffer)

	rounds, err := UpcomingGamesGA(betoffer, 2)
	if err != nil {
		t.Fatalf("UpcomingGamesGA: %v", err)
	}
	if len(rounds) != 2 {
		t.Fatalf("UpcomingGamesGA limit=2 returned %d", len(rounds))
	}
}

func TestRecentResultsGA_OnlyReturnsGA(t *testing.T) {
	resetForTest(t)
	if err := Init(filepath.Join(t.TempDir(), "ga_recent.db")); err != nil {
		t.Fatalf("init: %v", err)
	}
	defer resetForTest(t)

	const betoffer = 541
	seedMixedRoundsWithFinishedGA(t, betoffer)

	games, resMap, err := RecentResultsGA(betoffer, 10)
	if err != nil {
		t.Fatalf("RecentResultsGA: %v", err)
	}
	// 2 finished GA rounds seeded by helper.
	if len(games) != 2 {
		t.Fatalf("RecentResultsGA len=%d, want 2; rounds=%v", len(games), roundCodes(games))
	}
	for _, g := range games {
		if len(g.RoundCode) < 2 || g.RoundCode[:2] != "GA" {
			t.Fatalf("non-GA round leaked into RecentResultsGA: %s", g.RoundCode)
		}
		if g.Status != "F" {
			t.Fatalf("RecentResultsGA returned non-finished round: %s status=%s", g.RoundCode, g.Status)
		}
	}
	if resMap == nil {
		t.Fatal("RecentResultsGA: nil result map (want non-nil even when empty)")
	}
}

// TestOriginalGamesWindowReturnsAll is the regression test ensuring that
// adding the *GA helpers did NOT alter the behaviour of the un-suffixed
// GamesWindow. It must still return BOTH GA and numeric rounds.
func TestOriginalGamesWindowReturnsAll(t *testing.T) {
	resetForTest(t)
	if err := Init(filepath.Join(t.TempDir(), "all_window.db")); err != nil {
		t.Fatalf("init: %v", err)
	}
	defer resetForTest(t)

	const betoffer = 541
	seedMixedRoundsWithFinishedGA(t, betoffer)

	rounds, err := GamesWindow(betoffer, 10, 10)
	if err != nil {
		t.Fatalf("GamesWindow: %v", err)
	}
	// 3 DS finished + 2 GA finished + 3 GA open = 8.
	if len(rounds) != 8 {
		t.Fatalf("GamesWindow len=%d, want 8 (all rounds); rounds=%v", len(rounds), roundCodes(rounds))
	}

	hasNumeric, hasGA := false, false
	for _, r := range rounds {
		if len(r.RoundCode) >= 2 && r.RoundCode[:2] == "GA" {
			hasGA = true
		} else {
			hasNumeric = true
		}
	}
	if !hasGA || !hasNumeric {
		t.Fatalf("GamesWindow regressed: want both GA and numeric; hasGA=%v hasNumeric=%v", hasGA, hasNumeric)
	}
}

func roundCodes(rs []*models.GameRound) []string {
	out := make([]string, len(rs))
	for i, r := range rs {
		out[i] = r.RoundCode
	}
	return out
}

// =====================================================================
// Plan 04 DS-ISOLATION Task 1 — tests for the *DS mirror helpers.
//
// These tests assert the inverse contract of the *GA helpers above: the
// *DS family must filter OUT rounds whose RoundCode starts with "GA"
// (i.e. only DS-captured vendor rounds reach the ws-server). They mirror
// the seeding pattern of the *GA tests (seedMixedRounds /
// seedMixedRoundsWithFinishedGA) and add a couple of small extensions
// (seedMixedFutures, seedMixedRoundsWithResults, recovery helpers for
// the seeded codes) that the *GA tests did not need.
// =====================================================================

// seedMixedFutures inserts 3 DS-style rounds AND 3 GA-style rounds all in
// the FUTURE and OPEN. This is what UpcomingGamesDS expects to see (the
// existing seedMixedRounds has DS rounds in the past + finished, so
// UpcomingGamesDS would return nothing without this variant).
func seedMixedFutures(t *testing.T, betoffer int) {
	t.Helper()
	now := time.Now().UTC().Truncate(time.Second)
	mk := func(code string, ts time.Time) {
		gr := &models.GameRound{
			RoundCode:    code,
			GameTypeID:   betoffer,
			GameType:     "dog8",
			Status:       "O",
			VideoStartDt: ts.Format("2006-01-02 15:04:05"),
			VideoEndDt:   ts.Add(45 * time.Second).Format("2006-01-02 15:04:05"),
			CreatedAt:    ts.Format(time.RFC3339),
		}
		if _, err := UpsertGameRound(gr); err != nil {
			t.Fatalf("upsert %s: %v", code, err)
		}
	}
	// 3 DS open in future (offset 1..3 min).
	for i := 0; i < 3; i++ {
		ts := now.Add(time.Duration(i+1) * time.Minute)
		mk(toRoundCodeNumeric(betoffer, ts, i), ts)
	}
	// 3 GA open in future (offset 10..12 min so codes don't collide).
	for i := 0; i < 3; i++ {
		ts := now.Add(time.Duration(i+10) * time.Minute)
		mk(toRoundCodeGA(betoffer, ts, i), ts)
	}
}

// seedMixedRoundsWithResults builds on seedMixedRounds (3 DS finished + 3
// GA open) and additionally:
//   - upserts 2 GA FINISHED rounds (so RecentResultsDS must reject them),
//   - writes GameResults rows for every finished round (DS + GA) so the
//     StatsHistoryDS history rows have non-empty position arrays.
func seedMixedRoundsWithResults(t *testing.T, betoffer int) {
	t.Helper()
	seedMixedRoundsWithFinishedGA(t, betoffer)

	// Find every finished round and write a deterministic result for it.
	rows, err := db.Query(
		`SELECT RoundCode FROM GameRounds WHERE GameTypeId=? AND Status='F'`,
		betoffer,
	)
	if err != nil {
		t.Fatalf("list finished: %v", err)
	}
	defer rows.Close()
	var codes []string
	for rows.Next() {
		var c string
		if err := rows.Scan(&c); err != nil {
			t.Fatalf("scan finished: %v", err)
		}
		codes = append(codes, c)
	}
	for _, c := range codes {
		ft := 30.5
		results := []models.GameResult{
			{Position: 1, RunnerNumber: 7, FinishTime: &ft},
			{Position: 2, RunnerNumber: 3, FinishTime: nil},
		}
		if err := SaveResult(c, results); err != nil {
			t.Fatalf("SaveResult %s: %v", c, err)
		}
	}
}

// allSeededCodes returns every RoundCode currently in the GameRounds
// table for the given betoffer, in insertion-agnostic order. Used by the
// caller-side filter tests so they don't need to rebuild the synthetic
// codes the seed helpers produced.
func allSeededCodes(t *testing.T, betoffer int) []string {
	t.Helper()
	rows, err := db.Query(
		`SELECT RoundCode FROM GameRounds WHERE GameTypeId=?`,
		betoffer,
	)
	if err != nil {
		t.Fatalf("allSeededCodes query: %v", err)
	}
	defer rows.Close()
	var out []string
	for rows.Next() {
		var c string
		if err := rows.Scan(&c); err != nil {
			t.Fatalf("allSeededCodes scan: %v", err)
		}
		out = append(out, c)
	}
	return out
}

// firstDSCode returns one RoundCode that does NOT start with "GA".
func firstDSCode(t *testing.T, betoffer int) string {
	t.Helper()
	for _, c := range allSeededCodes(t, betoffer) {
		if !strings.HasPrefix(c, "GA") {
			return c
		}
	}
	t.Fatal("firstDSCode: no DS round seeded")
	return ""
}

// firstGACode returns one RoundCode that starts with "GA".
func firstGACode(t *testing.T, betoffer int) string {
	t.Helper()
	for _, c := range allSeededCodes(t, betoffer) {
		if strings.HasPrefix(c, "GA") {
			return c
		}
	}
	t.Fatal("firstGACode: no GA round seeded")
	return ""
}

func TestGamesWindowDS_FiltersGA(t *testing.T) {
	resetForTest(t)
	if err := Init(filepath.Join(t.TempDir(), "ds_window.db")); err != nil {
		t.Fatalf("init: %v", err)
	}
	defer resetForTest(t)

	const betoffer = 541
	seedMixedRoundsWithFinishedGA(t, betoffer) // 3 DS finished + 2 GA finished + 3 GA open

	rounds, err := GamesWindowDS(betoffer, 10, 10)
	if err != nil {
		t.Fatalf("GamesWindowDS: %v", err)
	}
	// Only the 3 DS finished rounds should survive (no DS open seeded).
	if len(rounds) != 3 {
		t.Fatalf("GamesWindowDS len=%d, want 3 DS-only; rounds=%v", len(rounds), roundCodes(rounds))
	}
	for _, r := range rounds {
		if strings.HasPrefix(r.RoundCode, "GA") {
			t.Fatalf("GA round leaked into DS path: %s", r.RoundCode)
		}
	}
}

func TestUpcomingGamesDS_FiltersGA(t *testing.T) {
	resetForTest(t)
	if err := Init(filepath.Join(t.TempDir(), "ds_upcoming.db")); err != nil {
		t.Fatalf("init: %v", err)
	}
	defer resetForTest(t)

	const betoffer = 541
	seedMixedFutures(t, betoffer) // 3 DS open + 3 GA open, all future

	rounds, err := UpcomingGamesDS(betoffer, 10)
	if err != nil {
		t.Fatalf("UpcomingGamesDS: %v", err)
	}
	if len(rounds) != 3 {
		t.Fatalf("UpcomingGamesDS len=%d, want 3 DS-only; rounds=%v", len(rounds), roundCodes(rounds))
	}
	for _, r := range rounds {
		if strings.HasPrefix(r.RoundCode, "GA") {
			t.Fatalf("GA leaked: %s", r.RoundCode)
		}
		if r.Status != "O" {
			t.Fatalf("UpcomingGamesDS returned non-open: %s status=%s", r.RoundCode, r.Status)
		}
	}
}

func TestStatsHistoryDS_FiltersGA(t *testing.T) {
	resetForTest(t)
	if err := Init(filepath.Join(t.TempDir(), "ds_stats.db")); err != nil {
		t.Fatalf("init: %v", err)
	}
	defer resetForTest(t)

	const betoffer = 541
	seedMixedRoundsWithResults(t, betoffer) // 3 DS finished + 2 GA finished, all with results

	hist, newest, oldest, err := StatsHistoryDS(betoffer, 20)
	if err != nil {
		t.Fatalf("StatsHistoryDS: %v", err)
	}
	if len(hist) != 3 {
		t.Fatalf("StatsHistoryDS got %d history rows, want 3 DS-only", len(hist))
	}
	if strings.HasPrefix(newest, "GA") || strings.HasPrefix(oldest, "GA") {
		t.Fatalf("StatsHistoryDS leaked GA newest=%s oldest=%s", newest, oldest)
	}
}

func TestGamesByRoundCodesDS_FiltersGAPrefix(t *testing.T) {
	resetForTest(t)
	if err := Init(filepath.Join(t.TempDir(), "ds_by_codes.db")); err != nil {
		t.Fatalf("init: %v", err)
	}
	defer resetForTest(t)

	const betoffer = 541
	seedMixedRounds(t, betoffer) // 3 DS finished + 3 GA open = 6 codes

	codes := allSeededCodes(t, betoffer)
	if len(codes) != 6 {
		t.Fatalf("seeded codes len=%d, want 6", len(codes))
	}
	rounds, err := GamesByRoundCodesDS(codes)
	if err != nil {
		t.Fatalf("GamesByRoundCodesDS: %v", err)
	}
	if len(rounds) != 3 {
		t.Fatalf("GamesByRoundCodesDS len=%d, want 3 DS-only", len(rounds))
	}
	for _, r := range rounds {
		if strings.HasPrefix(r.RoundCode, "GA") {
			t.Fatalf("GA leaked: %s", r.RoundCode)
		}
	}
}

func TestGameByRoundCodeDS_ReturnsNilForGA(t *testing.T) {
	resetForTest(t)
	if err := Init(filepath.Join(t.TempDir(), "ds_by_code.db")); err != nil {
		t.Fatalf("init: %v", err)
	}
	defer resetForTest(t)

	const betoffer = 541
	seedMixedRounds(t, betoffer)

	dsCode := firstDSCode(t, betoffer)
	r, err := GameByRoundCodeDS(dsCode)
	if err != nil || r == nil {
		t.Fatalf("expected DS round, got err=%v round=%v", err, r)
	}
	if r.RoundCode != dsCode {
		t.Fatalf("GameByRoundCodeDS got %s, want %s", r.RoundCode, dsCode)
	}

	gaCode := firstGACode(t, betoffer)
	r2, err := GameByRoundCodeDS(gaCode)
	if err != nil {
		t.Fatalf("expected no error for GA code, got %v", err)
	}
	if r2 != nil {
		t.Fatalf("expected nil for GA code, got %v", r2)
	}
}

func TestGamesByRoundCodesGA_FiltersDSPrefix(t *testing.T) {
	resetForTest(t)
	if err := Init(filepath.Join(t.TempDir(), "ga_by_codes.db")); err != nil {
		t.Fatalf("init: %v", err)
	}
	defer resetForTest(t)

	const betoffer = 541
	seedMixedRounds(t, betoffer) // 3 DS finished + 3 GA open = 6 codes

	codes := allSeededCodes(t, betoffer)
	if len(codes) != 6 {
		t.Fatalf("seeded codes len=%d, want 6", len(codes))
	}
	rounds, err := GamesByRoundCodesGA(codes)
	if err != nil {
		t.Fatalf("GamesByRoundCodesGA: %v", err)
	}
	if len(rounds) != 3 {
		t.Fatalf("GamesByRoundCodesGA len=%d, want 3 GA-only", len(rounds))
	}
	for _, r := range rounds {
		if !strings.HasPrefix(r.RoundCode, "GA") {
			t.Fatalf("DS leaked: %s", r.RoundCode)
		}
	}
}

func TestGameByRoundCodeGA_ReturnsNilForDS(t *testing.T) {
	resetForTest(t)
	if err := Init(filepath.Join(t.TempDir(), "ga_by_code.db")); err != nil {
		t.Fatalf("init: %v", err)
	}
	defer resetForTest(t)

	const betoffer = 541
	seedMixedRounds(t, betoffer)

	gaCode := firstGACode(t, betoffer)
	r, err := GameByRoundCodeGA(gaCode)
	if err != nil || r == nil {
		t.Fatalf("expected GA round, got err=%v round=%v", err, r)
	}
	if r.RoundCode != gaCode {
		t.Fatalf("GameByRoundCodeGA got %s, want %s", r.RoundCode, gaCode)
	}

	dsCode := firstDSCode(t, betoffer)
	r2, err := GameByRoundCodeGA(dsCode)
	if err != nil {
		t.Fatalf("expected no error for DS code, got %v", err)
	}
	if r2 != nil {
		t.Fatalf("expected nil for DS code, got %v", r2)
	}
}

func TestResultsByRoundCodeGA_FiltersDS(t *testing.T) {
	resetForTest(t)
	if err := Init(filepath.Join(t.TempDir(), "ga_results.db")); err != nil {
		t.Fatalf("init: %v", err)
	}
	defer resetForTest(t)

	const betoffer = 541
	seedMixedRoundsWithResults(t, betoffer) // 3 DS finished + 2 GA finished, all with results

	// A finished GA round (has results) must return them.
	var gaFinished string
	if err := db.QueryRow(
		`SELECT RoundCode FROM GameRounds WHERE GameTypeId=? AND Status='F' AND RoundCode LIKE 'GA%' LIMIT 1`,
		betoffer,
	).Scan(&gaFinished); err != nil {
		t.Fatalf("find finished GA: %v", err)
	}
	res, err := ResultsByRoundCodeGA(gaFinished)
	if err != nil {
		t.Fatalf("ResultsByRoundCodeGA: %v", err)
	}
	if len(res) == 0 {
		t.Fatalf("ResultsByRoundCodeGA(%s) returned no results", gaFinished)
	}

	// A DS round must be filtered out (nil, nil) without touching the DB.
	dsCode := firstDSCode(t, betoffer)
	res2, err := ResultsByRoundCodeGA(dsCode)
	if err != nil {
		t.Fatalf("expected no error for DS code, got %v", err)
	}
	if res2 != nil {
		t.Fatalf("expected nil results for DS code, got %v", res2)
	}
}

func TestGamesAfterGameIDDS_SkipsGAInWindow(t *testing.T) {
	resetForTest(t)
	if err := Init(filepath.Join(t.TempDir(), "ds_after.db")); err != nil {
		t.Fatalf("init: %v", err)
	}
	defer resetForTest(t)

	const betoffer = 541
	seedMixedRounds(t, betoffer) // DS in past, GA in future

	// Pivot on the oldest DS round so the future GA seeds fall AFTER it
	// (giving GA a real chance to leak if the filter is missing).
	pivot := firstDSCode(t, betoffer)
	rounds, err := GamesAfterGameIDDS(betoffer, pivot, 20)
	if err != nil {
		t.Fatalf("GamesAfterGameIDDS: %v", err)
	}
	for _, r := range rounds {
		if strings.HasPrefix(r.RoundCode, "GA") {
			t.Fatalf("GA leaked after pivot: %s", r.RoundCode)
		}
	}
}

func TestRecentResultsDS_FiltersGA(t *testing.T) {
	resetForTest(t)
	if err := Init(filepath.Join(t.TempDir(), "ds_recent.db")); err != nil {
		t.Fatalf("init: %v", err)
	}
	defer resetForTest(t)

	const betoffer = 541
	seedMixedRoundsWithResults(t, betoffer) // 3 DS finished + 2 GA finished

	rounds, resMap, err := RecentResultsDS(betoffer, 20)
	if err != nil {
		t.Fatalf("RecentResultsDS: %v", err)
	}
	if len(rounds) != 3 {
		t.Fatalf("RecentResultsDS len=%d, want 3 DS-only; rounds=%v", len(rounds), roundCodes(rounds))
	}
	for _, r := range rounds {
		if strings.HasPrefix(r.RoundCode, "GA") {
			t.Fatalf("GA leaked in results: %s", r.RoundCode)
		}
	}
	if resMap == nil {
		t.Fatal("RecentResultsDS: nil result map (want non-nil even when empty)")
	}
}

// TestGamesWindow_StillReturnsAll is the regression test ensuring that
// adding the *DS helpers did NOT alter the behaviour of GamesWindow.
// It must still return BOTH DS (numeric) and GA rounds.
func TestGamesWindow_StillReturnsAll(t *testing.T) {
	resetForTest(t)
	if err := Init(filepath.Join(t.TempDir(), "ds_regression.db")); err != nil {
		t.Fatalf("init: %v", err)
	}
	defer resetForTest(t)

	const betoffer = 541
	seedMixedRoundsWithFinishedGA(t, betoffer) // 3 DS F + 2 GA F + 3 GA O = 8

	rounds, err := GamesWindow(betoffer, 10, 10)
	if err != nil {
		t.Fatalf("GamesWindow: %v", err)
	}
	if len(rounds) != 8 {
		t.Fatalf("GamesWindow regressed: len=%d, want 8 (all rounds); rounds=%v", len(rounds), roundCodes(rounds))
	}
	hasNumeric, hasGA := false, false
	for _, r := range rounds {
		if strings.HasPrefix(r.RoundCode, "GA") {
			hasGA = true
		} else {
			hasNumeric = true
		}
	}
	if !hasGA || !hasNumeric {
		t.Fatalf("GamesWindow regressed: want both DS and GA; hasGA=%v hasNumeric=%v", hasGA, hasNumeric)
	}
}
